// Trading Bot Analytics Dashboard - server.js
// Port 3001 | Connects to trading-bot-pro.js bot API on port 3000

const express = require('express');
const cors = require('cors');
const fs = require('fs');
const path = require('path');
const { createObjectCsvWriter } = require('csv-writer');
const PDFDocument = require('pdfkit');

const app = express();
const PORT = 3001;
const BOT_API = process.env.BOT_API_URL || 'http://localhost:3000';
const LOGS_DIR = process.env.LOGS_DIR || './trading-logs';

app.use(cors());
app.use(express.json());
app.use(express.static(path.join(__dirname, 'public')));

// --- Utility: Parse trade logs from ./trading-logs/ ---
function parseTradeLogs() {
  const trades = [];
    if (!fs.existsSync(LOGS_DIR)) return trades;
      const files = fs.readdirSync(LOGS_DIR).filter(f => f.endsWith('.json') || f.endsWith('.log'));
        for (const file of files) {
            try {
                  const raw = fs.readFileSync(path.join(LOGS_DIR, file), 'utf8');
                        if (file.endsWith('.json')) {
                                const data = JSON.parse(raw);
                                        const arr = Array.isArray(data) ? data : (data.trades || [data]);
                                                trades.push(...arr);
                                                      } else {
                                                              raw.split('\n').filter(Boolean).forEach(line => {
                                                                        try { trades.push(JSON.parse(line)); } catch {}
                                                                                });
                                                                                      }
                                                                                          } catch {}
                                                                                            }
                                                                                              return trades;
                                                                                              }

                                                                                              // --- Compute analytics from trade data ---
                                                                                              function computeAnalytics(trades) {
                                                                                                const wins = trades.filter(t => (t.pnl || t.profit || 0) > 0);
                                                                                                  const losses = trades.filter(t => (t.pnl || t.profit || 0) <= 0);
                                                                                                    const winRate = trades.length ? (wins.length / trades.length * 100).toFixed(1) : 0;
                                                                                                    
                                                                                                      // Daily P&L (last 30 days)
                                                                                                        const now = Date.now();
                                                                                                          const daily = {};
                                                                                                            for (let i = 29; i >= 0; i--) {
                                                                                                                const d = new Date(now - i * 86400000).toISOString().split('T')[0];
                                                                                                                    daily[d] = 0;
                                                                                                                      }
                                                                                                                        trades.forEach(t => {
                                                                                                                            const d = new Date(t.timestamp || t.date || now).toISOString().split('T')[0];
                                                                                                                                if (daily[d] !== undefined) daily[d] += (t.pnl || t.profit || 0);
                                                                                                                                  });
                                                                                                                                  
                                                                                                                                    // Position heatmap (by symbol)
                                                                                                                                      const bySymbol = {};
                                                                                                                                        trades.forEach(t => {
                                                                                                                                            const sym = t.symbol || t.ticker || 'UNKNOWN';
                                                                                                                                                if (!bySymbol[sym]) bySymbol[sym] = { wins: 0, losses: 0, total: 0, pnl: 0 };
                                                                                                                                                    const pnl = t.pnl || t.profit || 0;
                                                                                                                                                        bySymbol[sym].pnl += pnl;
                                                                                                                                                            bySymbol[sym].total++;
                                                                                                                                                                pnl > 0 ? bySymbol[sym].wins++ : bySymbol[sym].losses++;
                                                                                                                                                                  });
                                                                                                                                                                  
                                                                                                                                                                    // Cumulative P&L for drawdown
                                                                                                                                                                      let peak = 0, maxDrawdown = 0, cumPnl = 0;
                                                                                                                                                                        const pnlSeries = trades.map(t => t.pnl || t.profit || 0);
                                                                                                                                                                          pnlSeries.forEach(p => {
                                                                                                                                                                              cumPnl += p;
                                                                                                                                                                                  if (cumPnl > peak) peak = cumPnl;
                                                                                                                                                                                      const dd = peak - cumPnl;
                                                                                                                                                                                          if (dd > maxDrawdown) maxDrawdown = dd;
                                                                                                                                                                                            });
                                                                                                                                                                                            
                                                                                                                                                                                              // Sharpe (simplified daily)
                                                                                                                                                                                                const dailyVals = Object.values(daily);
                                                                                                                                                                                                  const mean = dailyVals.reduce((a, b) => a + b, 0) / (dailyVals.length || 1);
                                                                                                                                                                                                    const variance = dailyVals.reduce((a, b) => a + Math.pow(b - mean, 2), 0) / (dailyVals.length || 1);
                                                                                                                                                                                                      const stdDev = Math.sqrt(variance);
                                                                                                                                                                                                        const sharpe = stdDev > 0 ? ((mean / stdDev) * Math.sqrt(252)).toFixed(2) : 0;
                                                                                                                                                                                                        
                                                                                                                                                                                                          // Execution speed
                                                                                                                                                                                                            const speeds = trades.filter(t => t.executionMs).map(t => t.executionMs);
                                                                                                                                                                                                              const avgSpeed = speeds.length ? (speeds.reduce((a, b) => a + b, 0) / speeds.length).toFixed(0) : 0;
                                                                                                                                                                                                              
                                                                                                                                                                                                                // Win/loss trend (10 most recent sessions grouped by day)
                                                                                                                                                                                                                  const trendDays = Object.keys(daily).slice(-10);
                                                                                                                                                                                                                    const winTrend = trendDays.map(d => {
                                                                                                                                                                                                                        const dayTrades = trades.filter(t => (new Date(t.timestamp || t.date || 0).toISOString().split('T')[0]) === d);
                                                                                                                                                                                                                            const w = dayTrades.filter(t => (t.pnl || t.profit || 0) > 0).length;
                                                                                                                                                                                                                                return { date: d, wins: w, total: dayTrades.length };
                                                                                                                                                                                                                                  });
                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                    return {
                                                                                                                                                                                                                                        summary: {
                                                                                                                                                                                                                                              totalTrades: trades.length,
                                                                                                                                                                                                                                                    wins: wins.length,
                                                                                                                                                                                                                                                          losses: losses.length,
                                                                                                                                                                                                                                                                winRate,
                                                                                                                                                                                                                                                                      totalPnl: pnlSeries.reduce((a, b) => a + b, 0).toFixed(2),
                                                                                                                                                                                                                                                                            maxDrawdown: maxDrawdown.toFixed(2),
                                                                                                                                                                                                                                                                                  sharpe,
                                                                                                                                                                                                                                                                                        avgExecutionMs: avgSpeed
                                                                                                                                                                                                                                                                                            },
                                                                                                                                                                                                                                                                                                dailyPnl: Object.entries(daily).map(([date, pnl]) => ({ date, pnl: +pnl.toFixed(2) })),
                                                                                                                                                                                                                                                                                                    heatmap: Object.entries(bySymbol).map(([symbol, v]) => ({ symbol, ...v, pnl: +v.pnl.toFixed(2) })),
                                                                                                                                                                                                                                                                                                        winTrend,
                                                                                                                                                                                                                                                                                                            speedBuckets: buildSpeedBuckets(speeds)
                                                                                                                                                                                                                                                                                                              };
                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                              function buildSpeedBuckets(speeds) {
                                                                                                                                                                                                                                                                                                                const buckets = { '<50ms': 0, '50-200ms': 0, '200-500ms': 0, '>500ms': 0 };
                                                                                                                                                                                                                                                                                                                  speeds.forEach(s => {
                                                                                                                                                                                                                                                                                                                      if (s < 50) buckets['<50ms']++;
                                                                                                                                                                                                                                                                                                                          else if (s < 200) buckets['50-200ms']++;
                                                                                                                                                                                                                                                                                                                              else if (s < 500) buckets['200-500ms']++;
                                                                                                                                                                                                                                                                                                                                  else buckets['>500ms']++;
                                                                                                                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                                                                                                                      return buckets;
                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                      // --- Routes ---
                                                                                                                                                                                                                                                                                                                                      app.get('/api/trades', async (req, res) => {
                                                                                                                                                                                                                                                                                                                                        const trades = parseTradeLogs();
                                                                                                                                                                                                                                                                                                                                          res.json({ trades, total: trades.length });
                                                                                                                                                                                                                                                                                                                                          });
                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                          app.get('/api/analytics', async (req, res) => {
                                                                                                                                                                                                                                                                                                                                            const trades = parseTradeLogs();
                                                                                                                                                                                                                                                                                                                                              const analytics = computeAnalytics(trades);
                                                                                                                                                                                                                                                                                                                                                res.json(analytics);
                                                                                                                                                                                                                                                                                                                                                });
                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                app.get('/api/positions', async (req, res) => {
                                                                                                                                                                                                                                                                                                                                                  const trades = parseTradeLogs();
                                                                                                                                                                                                                                                                                                                                                    const open = trades.filter(t => t.status === 'open' || !t.closeTime);
                                                                                                                                                                                                                                                                                                                                                      res.json({ positions: open });
                                                                                                                                                                                                                                                                                                                                                      });
                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                      // Proxy to bot API for live data
                                                                                                                                                                                                                                                                                                                                                      app.get('/api/bot/:endpoint', async (req, res) => {
                                                                                                                                                                                                                                                                                                                                                        try {
                                                                                                                                                                                                                                                                                                                                                            const axios = require('axios');
                                                                                                                                                                                                                                                                                                                                                                const response = await axios.get(`${BOT_API}/api/${req.params.endpoint}`, { timeout: 3000 });
                                                                                                                                                                                                                                                                                                                                                                    res.json(response.data);
                                                                                                                                                                                                                                                                                                                                                                      } catch (err) {
                                                                                                                                                                                                                                                                                                                                                                          res.json({ error: 'Bot API unavailable', fallback: true });
                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                            // Export CSV
                                                                                                                                                                                                                                                                                                                                                                            app.get('/export/csv', (req, res) => {
                                                                                                                                                                                                                                                                                                                                                                              const trades = parseTradeLogs();
                                                                                                                                                                                                                                                                                                                                                                                res.setHeader('Content-Type', 'text/csv');
                                                                                                                                                                                                                                                                                                                                                                                  res.setHeader('Content-Disposition', 'attachment; filename="trades-export.csv"');
                                                                                                                                                                                                                                                                                                                                                                                    const headers = ['Date', 'Symbol', 'Side', 'Quantity', 'EntryPrice', 'ExitPrice', 'PnL', 'ExecutionMs', 'Status'];
                                                                                                                                                                                                                                                                                                                                                                                      const rows = trades.map(t => [
                                                                                                                                                                                                                                                                                                                                                                                          t.timestamp || t.date || '', t.symbol || t.ticker || '',
                                                                                                                                                                                                                                                                                                                                                                                              t.side || t.type || '', t.qty || t.quantity || '',
                                                                                                                                                                                                                                                                                                                                                                                                  t.entryPrice || t.entry || '', t.exitPrice || t.exit || '',
                                                                                                                                                                                                                                                                                                                                                                                                      (t.pnl || t.profit || 0).toFixed(2), t.executionMs || '',
                                                                                                                                                                                                                                                                                                                                                                                                          t.status || 'closed'
                                                                                                                                                                                                                                                                                                                                                                                                            ]);
                                                                                                                                                                                                                                                                                                                                                                                                              res.write(headers.join(',') + '\n');
                                                                                                                                                                                                                                                                                                                                                                                                                rows.forEach(r => res.write(r.join(',') + '\n'));
                                                                                                                                                                                                                                                                                                                                                                                                                  res.end();
                                                                                                                                                                                                                                                                                                                                                                                                                  });
                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                  // Export PDF
                                                                                                                                                                                                                                                                                                                                                                                                                  app.get('/export/pdf', (req, res) => {
                                                                                                                                                                                                                                                                                                                                                                                                                    const trades = parseTradeLogs();
                                                                                                                                                                                                                                                                                                                                                                                                                      const analytics = computeAnalytics(trades);
                                                                                                                                                                                                                                                                                                                                                                                                                        const doc = new PDFDocument({ margin: 50 });
                                                                                                                                                                                                                                                                                                                                                                                                                          res.setHeader('Content-Type', 'application/pdf');
                                                                                                                                                                                                                                                                                                                                                                                                                            res.setHeader('Content-Disposition', 'attachment; filename="performance-report.pdf"');
                                                                                                                                                                                                                                                                                                                                                                                                                              doc.pipe(res);
                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                doc.fontSize(24).text('Trading Performance Report', { align: 'center' });
                                                                                                                                                                                                                                                                                                                                                                                                                                  doc.moveDown();
                                                                                                                                                                                                                                                                                                                                                                                                                                    doc.fontSize(12).text(`Generated: ${new Date().toLocaleDateString()}`, { align: 'center' });
                                                                                                                                                                                                                                                                                                                                                                                                                                      doc.moveDown(2);
                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                        const s = analytics.summary;
                                                                                                                                                                                                                                                                                                                                                                                                                                          doc.fontSize(16).text('Summary', { underline: true });
                                                                                                                                                                                                                                                                                                                                                                                                                                            doc.moveDown(0.5);
                                                                                                                                                                                                                                                                                                                                                                                                                                              doc.fontSize(11);
                                                                                                                                                                                                                                                                                                                                                                                                                                                doc.text(`Total Trades: ${s.totalTrades}`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                  doc.text(`Win Rate: ${s.winRate}%`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                    doc.text(`Total P&L: $${s.totalPnl}`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                      doc.text(`Max Drawdown: $${s.maxDrawdown}`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                        doc.text(`Sharpe Ratio: ${s.sharpe}`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                          doc.text(`Avg Execution Speed: ${s.avgExecutionMs}ms`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                            doc.moveDown(2);
                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                              doc.fontSize(16).text('Top Symbols by P&L', { underline: true });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                doc.moveDown(0.5);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  doc.fontSize(11);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const topSymbols = analytics.heatmap.sort((a, b) => b.pnl - a.pnl).slice(0, 10);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      topSymbols.forEach(sym => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          doc.text(`${sym.symbol}: $${sym.pnl} (${sym.wins}W / ${sym.losses}L)`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              doc.moveDown(2);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                doc.fontSize(16).text('Last 30 Days P&L', { underline: true });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  doc.moveDown(0.5);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    doc.fontSize(10);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      analytics.dailyPnl.slice(-10).forEach(d => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          const sign = d.pnl >= 0 ? '+' : '';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              doc.text(`${d.date}: ${sign}$${d.pnl}`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  doc.end();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  app.listen(PORT, () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    console.log(`Trading Analytics Dashboard running on http://localhost:${PORT}`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      console.log(`Reading trade logs from: ${path.resolve(LOGS_DIR)}`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        console.log(`Bot API endpoint: ${BOT_API}`);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        });
